export const actionTypes = {
    ADD_RECIPE: 'ADD_RECIPE',
    REMOVE_RECIPE: 'REMOVE_RECIPE',
    FETCH_LANDING: 'FETCH_LANDING',
    FETCH_FAVORITES: 'FETCH_FAVORITES',
    UPDATE_SELECTED: 'UPDATE_SELECTED',
};